#Stuff used by everyone
:rets_info: 
  :url: http://demo.crt.realtors.org:6103/rets/login
  :username: Joe
  :password: Schmoe
  #:user_agent: CRT-Data-Fetch/1.0
  #:user_agent_password: yourUserAgentPassword
  #:user_agent_auth_interealty: yes
  :rets_version: 1.7.2
  :log_file: yourlogfile.log
  
#Stuff needed for rets_data_fetch 
#:delimeter: ; #This defines the delimeter of the output file, comma is used if this is not present.
:resource: Property
:class: RES
#:limit: 100000
:select:
    - ListingID: ID
    - ListDate: Listing Date
    - ClosePrice: Final Sale Price
    - ListPrice
:dmql: (ListPrice=0+)

#Stuff used by object_fetch
:item_id: ID
:object_types:
    - Photo
